name: fakestore_custom_ui
description: FakeStore Flutter app with custom advanced UI
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.8
  lottie: ^2.7.0
  flutter_blurhash: ^0.8.2
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  go_router: ^16.2.4
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - Sale/
    - assets/animations/
    - assets/env/
